[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ImplicitCutIntegration = "f4391067-c08d-4a75-95e8-189e864e8de7"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Penguin = "c60b9c7f-4ba0-4cf4-9267-bf5bcdb56d21"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
