[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ILUZero = "88f59080-6952-5380-9ea5-54057fb9a43f"
ImplicitCutIntegration = "f4391067-c08d-4a75-95e8-189e864e8de7"
IncompleteLU = "40713840-3770-5561-ab4c-a76e7d0d7895"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
KrylovPreconditioners = "45d422c2-293f-44ce-8315-2cb988662dec"
LimitedLDLFactorizations = "f5a24dde-3ab7-510b-b81b-6a72c6098d3b"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Penguin = "c60b9c7f-4ba0-4cf4-9267-bf5bcdb56d21"
Preconditioners = "af69fa37-3177-5a40-98ee-561f696e4fcd"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
RandomizedPreconditioners = "3e7891d3-c9d1-416a-9949-ebd96150e4f0"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
